### ISSUE TITLE
Top Level Information copied down a level

### ISSUE THREAD

**Issue by jdhaines** [Chris1221/yamldoc#7]
Hi, great library!  I'm having a strange issue and I can't sort out where to fix it in the code.  If you give me a hint I could potentially submit a PR.

With small input files:

>demo.yaml

```yaml
#' ChangeDetailscomments
ChangeDetails:
  #' commit comments
  commit: 19393
  #' commitDate comments
  commitDate: 2023-06-02
  #' version comments
  version: 3.3.2
  #' repositoryLink comments
  repositoryLink: github
```

>demo.schema

```yaml
$schema: "https://json-schema.org/draft-04/schema#"

ChangeDetails:
  type: object

# or 
# type: object
# properties:
  # ChangeDetails:
  
  properties:
    commit:
      type: string
    commitDate:
      type: string
    version:
      type: string
    repositoryLink:
      type: string
    environmentBeforeChange:
      type: string
    environmentAfterChange:
      type: string
```

creates the markdown:

```md
Configuration Parameters Reference

Any information about this page goes here.

## `ChangeDetails`

 ChangeDetailscomments

### Member variables:

| Key | Value | Type | Information |
| :-: | :-: | :-: | :-- |
| `commit` | `19393` | string | ChangeDetailscomments commit comments |
| `commitDate` | `2023-06-02` | string | commitDate comments |
| `version` | `3.3.2` | string | version comments |
| `repositoryLink` | `github` | string | repositoryLink comments |
```

**Problem:** The _information_ for the top key (ChangeDetailscomments) is also put at the beginning of the information for the lower level key _commit_.  I'm not sure why, and printing various outputs from the python code didn't seem to give me a clue.

I'm seeing the same issue in your two level text example.  Thanks again for the cool library!
